2021-05-09 01:45:35,715 INFO    MainThread:26611 [internal.py:wandb_internal():91] W&B internal server running at pid: 26611, started at: 2021-05-09 01:45:35.715356
2021-05-09 01:45:35,721 DEBUG   HandlerThread:26611 [handler.py:handle_request():121] handle_request: run_start
2021-05-09 01:45:35,721 INFO    WriterThread:26611 [datastore.py:open_for_write():77] open: /home/trenton-windows/repos/spicy-dann/wandb/offline-run-20210509_014534-3qjlt2gm/run-3qjlt2gm.wandb
2021-05-09 01:45:35,778 DEBUG   HandlerThread:26611 [meta.py:__init__():39] meta init
2021-05-09 01:45:35,778 DEBUG   HandlerThread:26611 [meta.py:__init__():53] meta init done
2021-05-09 01:45:35,778 DEBUG   HandlerThread:26611 [meta.py:probe():210] probe
2021-05-09 01:45:35,781 DEBUG   HandlerThread:26611 [meta.py:_setup_git():200] setup git
2021-05-09 01:45:35,798 DEBUG   HandlerThread:26611 [meta.py:_setup_git():207] setup git done
2021-05-09 01:45:35,798 DEBUG   HandlerThread:26611 [meta.py:_save_pip():57] save pip
2021-05-09 01:45:35,798 DEBUG   HandlerThread:26611 [meta.py:_save_pip():71] save pip done
2021-05-09 01:45:35,798 DEBUG   HandlerThread:26611 [meta.py:_save_conda():78] save conda
2021-05-09 01:45:38,232 DEBUG   HandlerThread:26611 [meta.py:_save_conda():86] save conda done
2021-05-09 01:45:38,232 DEBUG   HandlerThread:26611 [meta.py:probe():252] probe done
2021-05-09 01:46:41,015 WARNING MainThread:26611 [internal.py:wandb_internal():147] Internal process interrupt: 1
2021-05-09 01:46:41,262 WARNING MainThread:26611 [internal.py:wandb_internal():147] Internal process interrupt: 2
2021-05-09 01:46:41,262 ERROR   MainThread:26611 [internal.py:wandb_internal():150] Internal process interrupted.
2021-05-09 01:46:41,752 INFO    SenderThread:26611 [sender.py:finish():925] shutting down sender
2021-05-09 01:46:41,957 INFO    WriterThread:26611 [datastore.py:close():258] close: /home/trenton-windows/repos/spicy-dann/wandb/offline-run-20210509_014534-3qjlt2gm/run-3qjlt2gm.wandb
2021-05-09 01:46:41,963 INFO    HandlerThread:26611 [handler.py:finish():632] shutting down handler
2021-05-09 01:46:41,964 INFO    MainThread:26611 [internal.py:handle_exit():78] Internal process exited
