2021-05-09 01:57:35,825 INFO    MainThread:27447 [internal.py:wandb_internal():91] W&B internal server running at pid: 27447, started at: 2021-05-09 01:57:35.824928
2021-05-09 01:57:35,830 DEBUG   HandlerThread:27447 [handler.py:handle_request():121] handle_request: run_start
2021-05-09 01:57:35,831 INFO    WriterThread:27447 [datastore.py:open_for_write():77] open: /home/trenton-windows/repos/spicy-dann/wandb/offline-run-20210509_015735-2cb2hsa6/run-2cb2hsa6.wandb
2021-05-09 01:57:35,872 DEBUG   HandlerThread:27447 [meta.py:__init__():39] meta init
2021-05-09 01:57:35,872 DEBUG   HandlerThread:27447 [meta.py:__init__():53] meta init done
2021-05-09 01:57:35,872 DEBUG   HandlerThread:27447 [meta.py:probe():210] probe
2021-05-09 01:57:35,874 DEBUG   HandlerThread:27447 [meta.py:_setup_git():200] setup git
2021-05-09 01:57:35,887 DEBUG   HandlerThread:27447 [meta.py:_setup_git():207] setup git done
2021-05-09 01:57:35,887 DEBUG   HandlerThread:27447 [meta.py:_save_pip():57] save pip
2021-05-09 01:57:35,887 DEBUG   HandlerThread:27447 [meta.py:_save_pip():71] save pip done
2021-05-09 01:57:35,887 DEBUG   HandlerThread:27447 [meta.py:_save_conda():78] save conda
2021-05-09 01:57:37,990 DEBUG   HandlerThread:27447 [meta.py:_save_conda():86] save conda done
2021-05-09 01:57:37,990 DEBUG   HandlerThread:27447 [meta.py:probe():252] probe done
2021-05-09 01:59:09,508 WARNING MainThread:27447 [internal.py:wandb_internal():147] Internal process interrupt: 1
2021-05-09 01:59:10,276 WARNING MainThread:27447 [internal.py:wandb_internal():147] Internal process interrupt: 2
2021-05-09 01:59:10,277 ERROR   MainThread:27447 [internal.py:wandb_internal():150] Internal process interrupted.
2021-05-09 01:59:10,850 INFO    SenderThread:27447 [sender.py:finish():925] shutting down sender
2021-05-09 01:59:11,085 INFO    WriterThread:27447 [datastore.py:close():258] close: /home/trenton-windows/repos/spicy-dann/wandb/offline-run-20210509_015735-2cb2hsa6/run-2cb2hsa6.wandb
2021-05-09 01:59:11,091 INFO    HandlerThread:27447 [handler.py:finish():632] shutting down handler
2021-05-09 01:59:11,092 INFO    MainThread:27447 [internal.py:handle_exit():78] Internal process exited
