2021-05-09 01:36:36,415 INFO    MainThread:26081 [internal.py:wandb_internal():91] W&B internal server running at pid: 26081, started at: 2021-05-09 01:36:36.415250
2021-05-09 01:36:36,420 DEBUG   HandlerThread:26081 [handler.py:handle_request():121] handle_request: run_start
2021-05-09 01:36:36,421 INFO    WriterThread:26081 [datastore.py:open_for_write():77] open: /home/trenton-windows/repos/spicy-dann/wandb/offline-run-20210509_013635-1nvc08wh/run-1nvc08wh.wandb
2021-05-09 01:36:36,467 DEBUG   HandlerThread:26081 [meta.py:__init__():39] meta init
2021-05-09 01:36:36,468 DEBUG   HandlerThread:26081 [meta.py:__init__():53] meta init done
2021-05-09 01:36:36,468 DEBUG   HandlerThread:26081 [meta.py:probe():210] probe
2021-05-09 01:36:36,470 DEBUG   HandlerThread:26081 [meta.py:_setup_git():200] setup git
2021-05-09 01:36:36,486 DEBUG   HandlerThread:26081 [meta.py:_setup_git():207] setup git done
2021-05-09 01:36:36,486 DEBUG   HandlerThread:26081 [meta.py:_save_pip():57] save pip
2021-05-09 01:36:36,486 DEBUG   HandlerThread:26081 [meta.py:_save_pip():71] save pip done
2021-05-09 01:36:36,487 DEBUG   HandlerThread:26081 [meta.py:_save_conda():78] save conda
2021-05-09 01:36:39,074 DEBUG   HandlerThread:26081 [meta.py:_save_conda():86] save conda done
2021-05-09 01:36:39,074 DEBUG   HandlerThread:26081 [meta.py:probe():252] probe done
2021-05-09 01:38:52,752 WARNING MainThread:26081 [internal.py:wandb_internal():147] Internal process interrupt: 1
2021-05-09 01:38:53,001 WARNING MainThread:26081 [internal.py:wandb_internal():147] Internal process interrupt: 2
2021-05-09 01:38:53,001 ERROR   MainThread:26081 [internal.py:wandb_internal():150] Internal process interrupted.
2021-05-09 01:38:53,447 INFO    SenderThread:26081 [sender.py:finish():925] shutting down sender
2021-05-09 01:38:53,812 INFO    WriterThread:26081 [datastore.py:close():258] close: /home/trenton-windows/repos/spicy-dann/wandb/offline-run-20210509_013635-1nvc08wh/run-1nvc08wh.wandb
2021-05-09 01:38:53,823 INFO    HandlerThread:26081 [handler.py:finish():632] shutting down handler
2021-05-09 01:38:53,824 INFO    MainThread:26081 [internal.py:handle_exit():78] Internal process exited
