2021-05-09 01:33:08,631 INFO    MainThread:25626 [internal.py:wandb_internal():91] W&B internal server running at pid: 25626, started at: 2021-05-09 01:33:08.628084
2021-05-09 01:33:08,639 INFO    WriterThread:25626 [datastore.py:open_for_write():77] open: /home/trenton-windows/repos/spicy-dann/wandb/offline-run-20210509_013307-1el09fy5/run-1el09fy5.wandb
2021-05-09 01:33:08,644 DEBUG   HandlerThread:25626 [handler.py:handle_request():121] handle_request: run_start
2021-05-09 01:33:08,713 DEBUG   HandlerThread:25626 [meta.py:__init__():39] meta init
2021-05-09 01:33:08,713 DEBUG   HandlerThread:25626 [meta.py:__init__():53] meta init done
2021-05-09 01:33:08,714 DEBUG   HandlerThread:25626 [meta.py:probe():210] probe
2021-05-09 01:33:08,715 DEBUG   HandlerThread:25626 [meta.py:_setup_git():200] setup git
2021-05-09 01:33:08,728 DEBUG   HandlerThread:25626 [meta.py:_setup_git():207] setup git done
2021-05-09 01:33:08,728 DEBUG   HandlerThread:25626 [meta.py:_save_pip():57] save pip
2021-05-09 01:33:08,728 DEBUG   HandlerThread:25626 [meta.py:_save_pip():71] save pip done
2021-05-09 01:33:08,728 DEBUG   HandlerThread:25626 [meta.py:_save_conda():78] save conda
2021-05-09 01:33:11,424 DEBUG   HandlerThread:25626 [meta.py:_save_conda():86] save conda done
2021-05-09 01:33:11,424 DEBUG   HandlerThread:25626 [meta.py:probe():252] probe done
2021-05-09 01:33:53,832 WARNING MainThread:25626 [internal.py:wandb_internal():147] Internal process interrupt: 1
2021-05-09 01:33:54,056 WARNING MainThread:25626 [internal.py:wandb_internal():147] Internal process interrupt: 2
2021-05-09 01:33:54,056 ERROR   MainThread:25626 [internal.py:wandb_internal():150] Internal process interrupted.
2021-05-09 01:33:54,667 INFO    SenderThread:25626 [sender.py:finish():925] shutting down sender
2021-05-09 01:33:54,845 INFO    WriterThread:25626 [datastore.py:close():258] close: /home/trenton-windows/repos/spicy-dann/wandb/offline-run-20210509_013307-1el09fy5/run-1el09fy5.wandb
2021-05-09 01:33:54,859 INFO    HandlerThread:25626 [handler.py:finish():632] shutting down handler
2021-05-09 01:33:54,875 INFO    MainThread:25626 [internal.py:handle_exit():78] Internal process exited
